version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/tmp/logs"
    volumes:
      - ./app_data/database:/var/lib/postgresql/data
      - ./app_data/logs/postgres:/var/postgres/logs
    healthcheck:
      test: pg_isready -U admin
      interval: 10s
      timeout: 10s
      retries: 3

  fake_twitter:
    image: "fake_twitter"
    container_name: fake_twitter
    build: fake_twitter
    environment:
      - API_KEYWORD=${API_KEYWORD}
      - ADMIN_LOGIN=${USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    entrypoint: uvicorn fake_twitter:app --host '0.0.0.0' --port 8000 --log-config /app/fake_twitter/log.ini
    volumes:
      - ./app_data/media:/app/app_static/media
      - ./app_data/logs/app:/app/log
    depends_on:
      postgres:
        condition: service_healthy


  tests:
    image: "fake_twitter_tests"
    container_name: tests
    build: tests
    restart: on-failure
    environment:
      - ADMIN_LOGIN=${USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - API_KEYWORD=${API_KEYWORD}
    volumes:
      - ./app_data/logs/tests:/tests/logs
    depends_on:
      fake_twitter:
        condition: service_started


  nginx:
      container_name: nginx
      restart: on-failure
      image: nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./app_data/logs/nginx:/var/log/nginx
        - ./static:/www/data
        - ./app_data/media:/www/data/static
      depends_on:
        tests:
          condition: service_completed_successfully
