version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/tmp/logs"
    ports:
      - '5432:5432'
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./logs:/var/postgres/logs
    healthcheck:
      test: pg_isready -U admin
      interval: 10s
      timeout: 3s
      retries: 3

#  nginx:
#    container_name: nginx
#    restart: always
#    image: nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./fake_twttr_app/static:/www/data/static
#      - ./fake_twttr_app/static/images:/www/data/static/images
