version: '3.9'

services:

  fake_twitter:
    image: "fake_twitter"
    container_name: fake_twitter
    build: fake_twttr_app
    entrypoint: uvicorn fake_twttr_app:app --host '0.0.0.0' --port 8000 --log-config /app/fake_twttr_app/log.ini
    volumes:
      - ./app_data/media:/app/fake_twttr_app/app/app_static/media
      - ./app_data/logs/app:/app/log
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/tmp/logs"
    volumes:
      - ./app_data/database:/var/lib/postgresql/data
      - ./app_data/logs/postgres:/var/postgres/logs
    healthcheck:
      test: pg_isready -U admin
      interval: 10s
      timeout: 3s
      retries: 3


  nginx:
      container_name: nginx
      restart: on-failure:5
      image: nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./app_data/logs/nginx:/var/log/nginx
        - ./static:/www/data
        - ./app_data/media:/www/data/static
      depends_on:
        fake_twitter:
          condition: service_started